# Generated by Django 4.0.6 on 2022-07-21 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todomodel_duedate_todomodel_priotity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todomodel',
            old_name='priotity',
            new_name='priority',
        ),
    ]
